# Generated by Django 3.0.7 on 2020-06-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_bot', '0002_auto_20200612_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viberuser',
            name='name',
            field=models.CharField(default='', max_length=75),
            preserve_default=False,
        ),
    ]
